#!/bin/sh

set -e

rm -f ackcc.i ackcc.k \
	ackcc.0.m ackcc.0.s ackcc.0.o ackcc.0.ack \
	ackcc.1.m ackcc.1.s ackcc.1.o ackcc.1.ack \
	ackcc.2.m ackcc.2.s ackcc.2.o ackcc.2.ack \
	ackcc.3.m ackcc.3.s ackcc.3.o ackcc.3.ack \
	a0.aout a1.out a2.out a3.out

./build/bin/cpp -I./toolchain/ack/libc -I./unix/v7/usr/include "$1" >ackcc.i
./build/bin/c1 -L -Vw2.2i2.2p4.2f4.2s2.2l4.2d8.2x8.2 ackcc.i ackcc.k

./build/bin/opt -n ackcc.k >ackcc.0.m
./build/bin/ncg ackcc.0.m ackcc.0.s
./build/bin/as - -o ackcc.0.o ackcc.0.s
./build/bin/led -o ackcc.0.ack ./build/toolchain/ack/68kunix/libc_crt0.o ackcc.0.o ./build/toolchain/ack/68kunix/libc.a ./build/toolchain/ack/68kunix/libc.a ./build/toolchain/ack/68kunix/libc_end.o
./build/bin/cv ackcc.0.ack a0.aout

echo "acklevels: wrote a0.aout"

./build/bin/opt ackcc.k >ackcc.1.m
./build/bin/ncg ackcc.1.m ackcc.1.s
./build/bin/as - -o ackcc.1.o ackcc.1.s
./build/bin/led -o ackcc.1.ack ./build/toolchain/ack/68kunix/libc_crt0.o ackcc.1.o ./build/toolchain/ack/68kunix/libc.a ./build/toolchain/ack/68kunix/libc.a ./build/toolchain/ack/68kunix/libc_end.o
./build/bin/cv ackcc.1.ack a1.out

echo "acklevels: wrote a1.out"

./build/bin/opt2 ackcc.k >ackcc.2.m
./build/bin/ncg ackcc.2.m ackcc.2.s
./build/bin/as - -o ackcc.2.o ackcc.2.s
./build/bin/led -o ackcc.2.ack ./build/toolchain/ack/68kunix/libc_crt0.o ackcc.2.o ./build/toolchain/ack/68kunix/libc.a ./build/toolchain/ack/68kunix/libc.a ./build/toolchain/ack/68kunix/libc_end.o
./build/bin/cv ackcc.2.ack a2.out

echo "acklevels: wrote a2.out"

if ./build/bin/opt3 ackcc.k >ackcc.3.m
then
	./build/bin/ncg ackcc.3.m ackcc.3.s
	./build/bin/as - -o ackcc.3.o ackcc.3.s
	./build/bin/led -o ackcc.3.ack ./build/toolchain/ack/68kunix/libc_crt0.o ackcc.3.o ./build/toolchain/ack/68kunix/libc.a ./build/toolchain/ack/68kunix/libc.a ./build/toolchain/ack/68kunix/libc_end.o
	./build/bin/cv ackcc.3.ack a3.out
	echo "acklevels: wrote a3.out"
else
	rm -f ackcc.3.m ackcc.3.s ackcc.3.o ackcc.3.ack a3.out
	echo "acklevels: opt3 not available, skipped a3.out"
fi
