s/_adf4/.adf4/g
s/_adf8/.adf8/g
s/_cff4/.cff4/g
s/_cff8/.cff8/g
s/_cfi/.cfi/g
s/_cfu/.cfu/g
s/_cif4/.cif4/g
s/_cif8/.cif8/g
s/_cmf4/.cmf4/g
s/_cmf8/.cmf8/g
s/_cuf4/.cuf4/g
s/_cuf8/.cuf8/g
s/_dvf4/.dvf4/g
s/_dvf8/.dvf8/g
s/_fef4/.fef4/g
s/_fef8/.fef8/g
s/_fif4/.fif4/g
s/_fif8/.fif8/g
s/_mlf4/.mlf4/g
s/_mlf8/.mlf8/g
s/_ngf4/.ngf4/g
s/_ngf8/.ngf8/g
s/_sbf4/.sbf4/g
s/_sbf8/.sbf8/g
s/_zrf4/.zrf4/g
s/_zrf8/.zrf8/g
s/_add_ext/.add_ext/g
s/_div_ext/.div_ext/g
s/_mul_ext/.mul_ext/g
s/_nrm_ext/.nrm_ext/g
s/_sft_ext/.sft_ext/g
s/_sub_ext/.sub_ext/g
s/_zrf_ext/.zrf_ext/g
s/_compact/.compact/g
s/_extend/.extend/g
s/_b64_add/.b64_add/g
s/_b64_sft/.b64_sft/g
s/_b64_rsft/.b64_rsft/g
s/_b64_lsft/.b64_lsft/g
