#!/bin/sh
set -e

project_dir=$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)
output=$project_dir/docs/syscalls.md
if test "$#" -gt 0
then
	case "$1" in
	/*) output=$1 ;;
	*) output=$project_dir/$1 ;;
	esac
fi

work_dir=$(mktemp -d "${TMPDIR-/tmp}/unix768-syscalls.XXXXXX")
trap 'rm -rf "$work_dir"' 0 1 2 3 15

sysent=$project_dir/unix/v7/usr/sys/sys/sysent.c
trap0=$project_dir/unix/v7/usr/sys/conf/trap0.c
libdir=$project_dir/toolchain/ack/libc/68kunix

awk '
/\/\*[[:space:]]*[0-9][0-9]*[[:space:]]*=/ {
	code = $0
	sub(/[[:space:]]*\/\*.*/, "", code)
	gsub(/[[:space:]]/, "", code)
	n = split(code, field, ",")
	if (n < 3)
		next

	comment = $0
	sub(/^.*\/\*[[:space:]]*/, "", comment)
	sub(/[[:space:]]*\*\/.*$/, "", comment)
	number = comment
	sub(/[[:space:]]*=.*$/, "", number)
	gsub(/[[:space:]]/, "", number)

	description = comment
	sub(/^.*=[[:space:]]*/, "", description)
	sub(/[[:space:]]*;.*/, "", description)

	handler = field[3]
	name = handler
	if (handler == "rexit") name = "exit"
	else if (handler == "gtime") name = "time"
	else if (handler == "sbreak") name = "break"
	else if (handler == "smount") name = "mount"
	else if (handler == "sumount") name = "umount"
	else if (handler == "saccess") name = "access"
	else if (handler == "ssig") name = "signal"
	else if (handler == "sysacct") name = "acct"
	else if (handler == "sysphys") name = "phys"
	else if (handler == "syslock") name = "lock"
	else if (number == 63) name = "internal"
	else if (handler == "nullsys" || handler == "nosys") {
		name = description
		sub(/[[:space:]].*$/, "", name)
	}

	printf "%d\t%s\t%s\t%s\t%s\n",
	    number, name, field[1], field[2], handler
}
' "$sysent" > "$work_dir/sysent"

awk '
/^[[:space:]]*case[[:space:]]+[0-9][0-9]*[[:space:]]*:/ {
	line = $0
	sub(/^[[:space:]]*case[[:space:]]+/, "", line)
	sub(/[[:space:]]*:.*/, "", line)
	print line
}
' "$trap0" > "$work_dir/trap0"

awk '
FNR == 1 {
	current = ""
	candidate = ""
}
/^_+[A-Za-z][A-Za-z0-9_]*:/ {
	label = $1
	sub(/:$/, "", label)
	current = label
	candidate = ""
	next
}
current != "" && /move[.]l[[:space:]]+#[0-9][0-9]*,d0/ {
	candidate = $0
	sub(/^.*#/, "", candidate)
	sub(/,d0.*$/, "", candidate)
	next
}
candidate != "" {
	if ($0 ~ /^[[:space:]]*trap[[:space:]]+#0/) {
		name = current
		sub(/^_+/, "", name)
		sub(/_raw$/, "", name)
		print candidate "\t" name
	}
	candidate = ""
}
' "$libdir"/*.s | sort -k1,1n -k2,2 -u > "$work_dir/wrappers.raw"

awk -F '\t' '
FILENAME == ARGV[1] {
	active[$1] = 1
	next
}
FILENAME == ARGV[2] {
	if (wrappers[$1] == "")
		wrappers[$1] = $2
	else
		wrappers[$1] = wrappers[$1] ", " $2
	next
}
BEGIN {
	print "<!-- Generated by host/scripts/gen-syscalls.sh; do not edit. -->"
	print ""
	print "# System calls"
	print ""
	print "The Epoch68 ABI enters the kernel with `trap #0` and the syscall number"
	print "in `d0`. Pointer, offset, time, and byte-count values are 32-bit."
	print "Descriptors, process and user IDs, modes, signals, and device selectors"
	print "retain their small V7 meanings."
	print ""
	print "This table is generated from the kernel system-entry table, the active"
	print "68000 trap dispatcher, and the ACK libc assembly veneers. A kernel-table"
	print "entry alone does not make a call usable: `trap0` must dispatch it, and"
	print "ordinary C programs normally also need a libc entry point."
	print ""
	print "| # | Name | Args | Register args | Kernel handler | trap0 | ACK libc |"
	print "| ---: | --- | ---: | ---: | --- | :---: | --- |"
}
FILENAME == ARGV[3] {
	number = $1
	veneer = wrappers[number]
	if (veneer == "")
		veneer = "—"
	dispatch = active[number] ? "yes" : "no"
	printf "| %d | `%s` | %s | %s | `%s` | %s | %s |\n",
	    number, $2, $3, $4, $5, dispatch, veneer
}
END {
	print ""
	print "Sources: `unix/v7/usr/sys/sys/sysent.c`,"
	print "`unix/v7/usr/sys/conf/trap0.c`, and"
	print "`toolchain/ack/libc/68kunix/*.s`."
	print ""
	print "Regenerate with `make docs`."
}
' "$work_dir/trap0" "$work_dir/wrappers.raw" "$work_dir/sysent" > "$output.tmp"
mv "$output.tmp" "$output"
