#ifndef REDPROTO_H
#define REDPROTO_H

/* System adaptation layer. */
int sysinit(void);
void sysend(void);
char *sysalloc(int n);
int sysmove(char source[], char dest[], int count);
int sysintr(int systl, int systy, int sysn);
int syscstat(void);
int syscin(void);
int syswait(void);
int syscout(int c);
int syslout(int c);
FILE *sysfcreat(char *filename, FILE *buffer);
FILE *sysfopen(char *filename, FILE *buffer);
int sysfclose(FILE *fd);
int sysfflush(FILE *fd);
int sysgetc(FILE *fd);
int sysfgets(FILE *fd, char *buffer, int maxlen);
int sysputc(int c, FILE *fd);
int syscreat(char *filename);
int sysopen(char *name, int mode);
int sysclose(int fd);
int sysunlink(char *filename);
int sysrename(char *oldname, char *newname);
int sysseek(int fd, int block);
int sysread(int fd, char *buffer);
int syswrite(int fd, char *buffer, int n);
int sysexists(char *filename);
int syscopfn(char *args, char *buffer);

/* ports/red/red10.c */
/* ports/red/red11.c */
/* ports/red/red12.c */
/* ports/red/red13.c */
/* ports/red/red2.c */
/* ports/red/red3.c */
/* ports/red/red4.c */
/* ports/red/red5.c */
/* ports/red/red6.c */
/* ports/red/red7.c */
/* ports/red/red9.c */
char *b1_ptr(int line);
char *b_ptr(struct BLOCK *bp, int line);
int put_buf(int avail);
char *skiparg(char *args);
char *skipbl(char *args);
int _combine(int diskp1, int diskp2);
int amatch(char *line, char *pat);
int append(char *fname, int where, char *prompt);
int b1_avail(void);
int b1_length(int line);
int b1_nlines(void);
int b1_prefix(int line);
int b1_settab(int index, int value);
int b1_tab(int index);
int b_avail(struct BLOCK *bp);
int b_getnum(char *p);
int b_length(struct BLOCK *bp, int line);
int b_nlines(struct BLOCK *bp);
int b_prefix(struct BLOCK *bp, int line);
int b_putnum(char *p, int num);
int b_settab(struct BLOCK *bp, int index, int value);
int b_tab(struct BLOCK *bp, int index);
int buf_clr(void);
int buf_d(int nlines);
int buf_gobk(void);
int buf_gofw(void);
int bufatbot(void);
int bufattop(void);
int bufchng(void);
int bufdel(void);
int bufdeln(int nlines);
int bufdn(void);
int bufend(void);
int bufgetln(char *line, int linelen);
int bufgo(int n);
int bufinit(void);
int bufins(char insline[], int inslen);
int bufln(void);
int bufmax(void);
int bufnew(void);
int bufnrbot(void);
int bufout(int topline, int topy, int nlines);
int bufoutln(int line);
int bufrepl(char line[], int n);
int bufsaved(void);
int bufup(void);
int cant_happen(char *message);
int change(char *args);
int check_block(char *message);
int chkbuf(void);
int chkckey(void);
int chkkey(void);
int clear1(void);
int cmndmess(char *mess);
int combine(void);
int command(void);
int control(int c);
int copy(char *args);
int data_open(void);
int del_bl(int nlines);
int del_mid(int dlines);
int del_tail(int slines, int nlines);
int delete(char *args);
int disk_error(char *message);
int disk_full(void);
int disk_rdy(void);
int do_lru(struct BLOCK *bp);
int dump_block(struct BLOCK *bp);
int dump_memory(void);
int dump_vars(void);
int ed2del(void);
int ed_del(void);
int ed_ind(void);
int ed_inu(void);
int ed_sdn(int topline);
int ed_sup(int topline);
int edabt(void);
int edadj(void);
int edatbot(void);
int edattop(void);
int edbegin(void);
int edbword(void);
int edchng(int c);
int edclr(void);
int eddel(void);
int eddn(void);
int edend(void);
int edfword(void);
int edgetln(void);
int edgo(int newline, int x);
int edins(int c);
int edjoin(void);
int edkill(int c);
int edleft(void);
int ednewdn(void);
int ednewup(void);
int edredraw(void);
int edrepl(void);
int edright(void);
int edscan(int xpos);
int edsplit(void);
int edsrch(int c);
int edup(void);
int edxpos(void);
int edzap(void);
int error(char *message);
int extract(char *args);
int find(char *args);
int findr(char *args);
int fmtadj(char *buf, int minind, int maxind);
int fmtassn(int listflag);
int fmtcrlf(void);
int fmtdevch(int c);
int fmtlen(char *buf, int i);
int fmtlench(int c, int col);
int fmtoutch(int c, int col);
int fmtset(int n);
int fmtsout(char *buf, int offset);
int fmtsubs(char *buf, int i, int j);
int free_block(struct BLOCK *bp);
int get3args(char *args, int *val1, int def1, int *val2, int def2, int *val3, int def3);
int getcmnd(char *args);
int help(void);
int inject(char *args);
int is_dirty(struct BLOCK *bp);
int itoc(int n, char *str, int size);
int list(char *args);
int load(char *args);
int lookup(char *line, char *cmnd);
int main(int argc, char **argv);
int message(char *s);
int move(char *args);
int movecopy(char *args, char *usage, char *prompt, int erase);
int name(char *args);
int name1(char *args, char *filename);
int number(char *args, int *val);
int outchar(int c);
int outclr(void);
int outdel(void);
int outdelln(void);
int outdeol(void);
int outgetx(void);
int outgety(void);
int outinit(void);
int outins(void);
int outsdn(void);
int outsup(void);
int outxy(int x, int y);
int pmt1upd(int x);
int pmtclr(void);
int pmtfn(void);
int pmthold(int flag);
int pmtlast(void);
int pmtmess(char *s1, char *s2);
int pmtmode(char *newmode);
int pmtupd(void);
int pmtzap(void);
int put_block(struct BLOCK *bp, int diskp);
int put_slot(struct BLOCK *bp);
int putdec(int n, int w);
int read1(void);
int read2(void);
int read_file(char file_name[]);
int replace(char *oldline, char *newline, char *oldpat, char *newpat, int col);
int resave(void);
int save(void);
int search(char *args);
int srch1(int s_start, int s_end, int r_flag, int w_flag, int c_flag);
int srch2(char *old_pat, char *new_pat, int r_flag, int c_flag, int *a_flag, int s_anchor, int e_anchor, int plen);
int swap_all(void);
int swap_one(void);
int swap_sync(int low, int high);
int tabs(char *args);
int warning(char *message);
int wr_flush(void);
int write1(int c);
int write_file(char *file_name);
int xtrct(char *fname, int start, int finish, char *prompt);
struct BLOCK *new_block(void);
struct BLOCK *split_block(void);
struct BLOCK *swap_in(int diskp);
struct BLOCK *swap_new(int diskp);
struct BLOCK *swap_out(void);

#endif
